In [3]:
import numpy as np
from numpy.ma.core import where

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr0=np.array([5, 10, 15, 20, 25])
arr0.sum()
arr0.mean()

np.float64(15.0)

In [24]:
list=[]
for i in range(0,20):
    if i%2==0:
        list.append(i)
        arr1=np.array(list)

In [25]:
arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
arr2=np.array([10,20,30,40,50,60,70])

In [42]:
arr2[0:3]
arr2[-2:]
arr2[1:5]

array([20, 30, 40, 50])

In [43]:
arr3=[[1,2,3],
 [4,5,6],
 [7,8,9]]

In [48]:
arr3[1]

[4, 5, 6]

In [50]:
arr5 = np.arange(1,21,5)

In [53]:
arr5
print(arr5**2)
arr5.shape

[  1  36 121 256]

(4,)

In [61]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

In [64]:
arr[:,3]
arr[:,1]
arr[2]

array([ 9, 10, 11, 12])

In [1]:
import numpy as np

In [7]:
arr6=np.arange(0,9)

In [8]:
arr6.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
arr7=np.arange(0,16)

In [10]:
arr7.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
arr7[1]

np.int64(1)

In [15]:
arr8=np.arange(0,25)

In [22]:
arr9=arr8.reshape(5,5)

In [24]:
arr9[3]

array([15, 16, 17, 18, 19])

In [31]:
arr10=np.arange(0,288)
arr10

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287])

In [32]:
arr11=arr10.reshape(2,3,2,6,4)

In [33]:
arr11

array([[[[[  0,   1,   2,   3],
          [  4,   5,   6,   7],
          [  8,   9,  10,  11],
          [ 12,  13,  14,  15],
          [ 16,  17,  18,  19],
          [ 20,  21,  22,  23]],

         [[ 24,  25,  26,  27],
          [ 28,  29,  30,  31],
          [ 32,  33,  34,  35],
          [ 36,  37,  38,  39],
          [ 40,  41,  42,  43],
          [ 44,  45,  46,  47]]],


        [[[ 48,  49,  50,  51],
          [ 52,  53,  54,  55],
          [ 56,  57,  58,  59],
          [ 60,  61,  62,  63],
          [ 64,  65,  66,  67],
          [ 68,  69,  70,  71]],

         [[ 72,  73,  74,  75],
          [ 76,  77,  78,  79],
          [ 80,  81,  82,  83],
          [ 84,  85,  86,  87],
          [ 88,  89,  90,  91],
          [ 92,  93,  94,  95]]],


        [[[ 96,  97,  98,  99],
          [100, 101, 102, 103],
          [104, 105, 106, 107],
          [108, 109, 110, 111],
          [112, 113, 114, 115],
          [116, 117, 118, 119]],

         [[120, 121, 122, 123],
          [124, 125, 126, 127],
          [128, 129, 130, 131],
          [132, 133, 134, 135],
          [136, 137, 138, 139],
          [140, 141, 142, 143]]]],



       [[[[144, 145, 146, 147],
          [148, 149, 150, 151],
          [152, 153, 154, 155],
          [156, 157, 158, 159],
          [160, 161, 162, 163],
          [164, 165, 166, 167]],

         [[168, 169, 170, 171],
          [172, 173, 174, 175],
          [176, 177, 178, 179],
          [180, 181, 182, 183],
          [184, 185, 186, 187],
          [188, 189, 190, 191]]],


        [[[192, 193, 194, 195],
          [196, 197, 198, 199],
          [200, 201, 202, 203],
          [204, 205, 206, 207],
          [208, 209, 210, 211],
          [212, 213, 214, 215]],

         [[216, 217, 218, 219],
          [220, 221, 222, 223],
          [224, 225, 226, 227],
          [228, 229, 230, 231],
          [232, 233, 234, 235],
          [236, 237, 238, 239]]],


        [[[240, 241, 242, 243],
          [244, 245, 246, 247],
          [248, 249, 250, 251],
          [252, 253, 254, 255],
          [256, 257, 258, 259],
          [260, 261, 262, 263]],

         [[264, 265, 266, 267],
          [268, 269, 270, 271],
          [272, 273, 274, 275],
          [276, 277, 278, 279],
          [280, 281, 282, 283],
          [284, 285, 286, 287]]]]])

In [37]:
arr11.ndim
1
33
58
102
143
215

215

In [43]:
arr11[0,0,0,0,1]

np.int64(1)

In [49]:
arr11[0,0,1,2,1]

np.int64(33)

In [54]:
arr11[0,1,0,2,2]

np.int64(58)

In [60]:
arr11[0,2,0,1,2]

np.int64(102)

In [67]:
arr11[0,2,1,5,3]

np.int64(143)

In [74]:
arr11[1,1,0,5,3]

np.int64(215)

In [89]:
arr12=np.arange(0,60)

In [90]:
arr13=arr12.reshape(2,5,6)

In [92]:
arr13

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]]])

In [97]:
arr13[0,3: ,4:]

array([[22, 23],
       [28, 29]])

In [88]:
#long matrix ke slicing ka lia hum pahla row oska bad coulm

In [5]:
import numpy as np

In [6]:
arrd=np.arange(0,30)

In [8]:
arrf=arrd.reshape(5,6)

In [9]:
arrf

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [10]:
arrf.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

arrf.flatten()  are change into one dimension

In [11]:
arrf.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [13]:
np.sqrt(arrf)
np.sin(arrf)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
        -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
        -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784, -0.28790332,
        -0.96139749],
       [-0.75098725,  0.14987721,  0.91294525,  0.83665564, -0.00885131,
        -0.8462204 ],
       [-0.90557836, -0.13235175,  0.76255845,  0.95637593,  0.27090579,
        -0.66363388]])

In [19]:
tbt=np.arange(0,50)

In [30]:
tbt[(tbt>10)&(tbt<40)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

where() and filter

In [2]:
import pandas as  pd

In [48]:

sr=pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'])

In [49]:
sr

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [28]:
dic={"name":["umar","farooq","ali"],
"age":[20,21,23]}

In [29]:
df=pd.DataFrame(dic)

In [30]:
df.to_csv("classfirsttable.csv")

In [62]:
df

     name  age
0    umar   20
1  farooq   21
2     ali   23

In [24]:
df1=pd.read_excel("VendorProducts.xlsx",sheet_name="Items")

df2=pd.read_excel("VendorProducts.xlsx",sheet_name="Collections")

In [25]:
df2

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Color,Secondary Color,Size,Unit Level,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"420,000د.ع",3145891072204,82528.0,100 مل,100 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"300,000د.ع",3145891072105,82755.0,50 مل,50 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك,The Glow Stick,#F3D5C6,"19,750د.ع",7333352079169,82570.0,24 سباركلينج بيج,24 Sparkling Beige,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك,The Glow Stick,#F2B2B9,"19,750د.ع",7333352079176,82571.0,25 روز جليم,25 Rose Gleam,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك,The Contour Stick,#AF8E7A,"19,750د.ع",7333352079084,82565.0,30,30,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل,Instant Anti Age Eraser Concealer 6 ml,#F5D4C5,"17,250د.ع",3600530733866,58724.0,03 معتدل,03 Fair,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"17,000د.ع",697029058770,60467.0,500 مل,500 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"6,500د.ع",697029602478,81429.0,88.7 مل,88.7 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"17,000د.ع",697029041260,47028.0,500 مل,500 ml,NaN,Level1,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"6,500د.ع",697029532409,81431.0,88.7 مل,88.7 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...

In [34]:
df1.columns

Index(['Picture', 'Id', 'Name', 'Secondary Name', 'Barcode', 'Code', 'Price',
       'Description', 'Secondary Description', 'Sub Description',
       'Secondary Sub Description', 'Menu', 'Brand', 'Secondary Brand',
       'Has Collections'],
      dtype='str')

In [39]:
df4=df1['Price']

In [46]:
df5=list[df4]

In [47]:
for i in df5:
    print(df5.replace(""))

list[0         25,000د.ع
1        300,000د.ع
2         30,000د.ع
3             00د.ع
4         15,000د.ع
            ...
24697     16,500د.ع
24698     12,000د.ع
24699     10,500د.ع
24700     15,000د.ع
24701     22,500د.ع
Name: Price, Length: 24702, dtype: str]

In [48]:
import numpy as np

In [61]:
arr=np.arange(1,50,)[arr%2==0]
arr
arr1=np.arange(0,9)
arr2=arr1.reshape(3,3)
arr2=arr1.reshape(3,3)
arr3=arr2[0].sum()
arr4=arr2[1].sum()
arr5=arr2[2].sum()
np.array([arr3,arr4,arr5])
arr6=np.arange(0,10)
arr6.max()
arr7=np.arange(0,16).reshape(4,4)
arr7[:,1]
arr8=np.arange(0,10)
arr9=arr8*2
arr9
arrq=[10,20,30,40,50]
arrq[2]=300
arrq
arrw=np.arange(0,100)
arrw[arrw>50]
arr7.diagonal()

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])