In [21]:
import pandas as pd

while True:
    choise= input("Enter your choice:"
                   "\n 1:create account: "
                   "\n 2:check  balance:"
                   "\n 3:withDraw amount"
                   "\n 4:Deposit amount"
                  "\n 5:Exist"
                   )
    if choise == "1":
        name=input("Enter your name:")
        acc=input("Enter your account:")
        if acc in useracc["account"]:
            print("Account already exist")
        else:
         useracc["name"].append(name)
         useracc["account"].append(acc)
         useracc["balance"].append(5000)
    elif choise == "2":
        pd.read_csv("accounts.csv")
        acc=int(input("Enter your account number:"))
        for i in range(len(useracc)):
            useracc["account"][i]=acc
            nm=useracc["name"][i]
            print(f" {nm} you current is { useracc["balance"][i]}")
    elif choise == "3":
        pd.read_csv("accounts.csv")
        acc=int(input("Enter your account number:"))
        for i in range(len(useracc)):
            useracc["account"][i]=acc
            nm=useracc["name"][i]
            amount=int(input("Enter your amount:"))
            blance=useracc["balance"][i]-amount
            print(f" {nm} you current  blance is { blance}")
    elif choise == "4":
          pd.read_csv("accounts.csv")
          acc=int(input("Enter your account number:"))
          for i in range(len(useracc)):
            useracc["account"][i]=acc
            nm=useracc["name"][i]
            amount=int(input("Enter your amount:"))
            blance=useracc["balance"][i]+amount
            print(f" {nm} you current  blance is { blance}")
    elif choise == "5":
        print("exist")
        break
        useracc={"name":["umar"],"account":[103],"balance":[5000,]}
        df=pd.DataFrame(useracc)
        d=df.to_csv("accounts.csv")

KeyboardInterrupt: Interrupted by user

In [17]:
useracc={"name":["umar"],"account":[103],"balance":[5000,]}
df=pd.DataFrame(useracc)
d=df.to_csv("accounts.csv")

In [2]:
import pandas as pd

In [3]:
while True:
     choise= input("Enter your choice:"
                   "\n 1:student registration : "
                   "\n 2:student information fetch:"
                   "\n 3:student information:"
                  "\n 4:Exist"
                   )
     if choise == "1":
         df=pd.read_csv("students.csv")
         userid=int(input("Enter your student id:"))
         username=input("Enter your student username:")
         clas=input("Enter your student class:")
         subject=input([])
         if userid in Studentdata["userid"]:
           print("you are already registered")
         else:
           Studentdata["userid"].append(userid)
           Studentdata["username"].append(username)
           Studentdata["clas"].append(clas)
           Studentdata["subject"].append(subject)
           df=pd.DataFrame(Studentdata)
           df=df.to_csv("students.csv",index=False)
     elif choise == "2":
         df=pd.read_csv("students.csv")
         id=int(input("Enter your student id:"))
         if id not in list(Studentdata["userid"]):
             print("not found")
             continue
         for inf in range(len(Studentdata["userid"])):
             if id==Studentdata["userid"][inf]:
                print(Studentdata["username"][inf])
                print(Studentdata["clas"][inf])
                print(Studentdata["subject"][inf])
     elif choise == "3":
        print("")
     elif choise == "4":
         break

KeyboardInterrupt: Interrupted by user

In [4]:
Studentdata={"userid":[101],"username":["umar"],"clas":["BSSE"],"subject":[[["math","english","bio"]]]}
df=pd.DataFrame(Studentdata)
df.to_csv("students.csv",index=False)

In [69]:
df

   userid username  clas                 subject
0     101     umar  BSSE  [[math, english, bio]]

In [35]:
df

   userid username  clas subject
0     101     umar  BSSE      SE
1     102   farooq  BSCS      CS

In [5]:
import pandas as pd

In [6]:
StudentAccountDictionary = {"StudentId":["10001","10002","10003"],"StudentName":["Ahmad","Ali","yth"],"StudentClass":["1","2","3"],"Subjects":[["Math","English","Science"],["Math","Chemistry","Science"],["islamicStudies","English","Physics"]]}
studentDF = pd.DataFrame(StudentAccountDictionary)
studentDF.to_csv("StudentData.csv",index=False)

In [7]:
while True:
    choice = input("Enter 1 for Student Registration \n Enter 2 for Student Information Fetch \n Enter 3 for Student Information Update \n Enter 4 for Exit:")
    if choice == "1":
        print("Student Registration")
        studentDF = pd.read_csv("StudentData.csv")
        studentId = input("Enter Student Id:")
        newStudentName=input("enter new name ")
        studentclass=input("enter new class ")
        subject=["Math","English","Science","Physics"]
        if studentId not in list(studentDF["StudentId"]):
            print("not found")
        else:
            StudentAccountDictionary["StudentId"].append(studentId)
            StudentAccountDictionary["StudentName"].append(newStudentName)
            StudentAccountDictionary["StudentClass"].append(studentclass)
            StudentAccountDictionary["Subjects"].append(subject)
            studentDF = pd.DataFrame(StudentAccountDictionary)
            studentDF.to_csv("StudentData.csv",index=False)




    elif choice =="2":
        print("======Student Information Fetch========")
        studentDF = pd.read_csv("StudentData.csv")
        studentId = input("Enter Student Id:")
        if studentId not in list(studentDF["StudentId"]):
            print("Student Id Not Found")
            continue
        for i in range(len(studentDF)):
            if studentDF["StudentId"][i] == studentId:
                print(f"Student Name : {studentDF['StudentName'][i]}")
                print(f"Student Class : {studentDF['StudentClass'][i]}")
                print(f"Student Subjects : {studentDF['Subjects'][i]}")
        print("======Student Information Fetch========")
    elif choice =="3":
        print("======Student Information Update=======")
        studentDF = pd.read_csv("StudentData.csv")
        studentId = input("Enter Student Id:")
        if studentId not in list(studentDF["StudentId"]):
            print("Student Id Not Found")
            continue
        for i in range(len(studentDF)):
            if studentDF["StudentId"][i] == studentId:
                print("What do you want to update?")
                updateChoice = input("Enter 1 for Student Name \n Enter 2 for Student Class \n Enter 3 for Student Subjects:")
                if updateChoice == "1":
                    newStudentName = input("Enter New Student Name:")
                    studentDF['StudentName'][i] = newStudentName
                    print(f"Student Name Updated to {newStudentName}")
                elif updateChoice == "2":
                    newStudentClass = input("Enter New Student Class:")
                    studentDF['StudentClass'][i] = newStudentClass
                    print(f"Student Class Updated to {newStudentClass}")
                elif updateChoice == "3":
                     cho = input("Enter choice:\n1:add subject\n2:remove subject\n")
                     subjects = studentDF["Subjects"][i].split(",")

                     if cho == "1":
                         newSub = input("Enter subject to add: ")
                         subjects.append(newSub)
                         studentDF["Subjects"][i] = str(subjects)
                     elif cho == "2":
                          newSubjects = input("Enter subjects separated by comma: ")
                          studentDF["Subjects"][i] = newSubjects



                     studentDF.to_csv("StudentData.csv", index=False)
                     print("Student Information Updated Successfully")
    elif choice =="4":
        print("Exiting")
        break

Student Registration
not found
Exiting